version: '3'
services:
  vos-mysql:
    image: mysql:latest
    ports:
      - '${MYSQL_BINDING_PORT}:${MYSQL_PORT}'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - vos:/db
    container_name: vos-mysql

volumes:
  vos: